Alias: $exp = http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation

Instance: twiin-subscription-server
InstanceOf: CapabilityStatement
Usage: #definition
Title: "Twiin Subscription Server"
Description: "Requirements for a Subscription Server under TA Notifications (TA section System Roles and Responsibilities → Subscription Server). Imports the Backport IG Subscription Server CapabilityStatement for R4."
* url = "https://fhir.twiin.nl/ig/notifications/CapabilityStatement/twiin-subscription-server"
* name = "TwiinSubscriptionServer"
* title = "Twiin Subscription Server"
* status = #draft
* experimental = false
* date = "2026-10-08"
* kind = #requirements
* imports = "http://hl7.org/fhir/uv/subscriptions-backport/CapabilityStatement/backport-subscription-server-r4|1.1.0"
* fhirVersion = #4.0.1
* format[0] = #json
* format[0].extension[0].url = $exp
* format[0].extension[0].valueCode = #SHALL
* format[1] = #xml
* format[1].extension[0].url = $exp
* format[1].extension[0].valueCode = #SHALL
* rest[0].mode = #server
* rest[0].documentation = "Where the Subscription Server supports in-band Subscription creation, it SHOULD advertise the SubscriptionTopics it supports with the extension http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/capabilitystatement-subscriptiontopic-canonical (TA section Subscription Server)."
* rest[0].security.service = http://terminology.hl7.org/CodeSystem/restful-security-service#Certificates
* rest[0].security.description = "All endpoints are secured with mutual TLS (TA section Preconditions)."
* rest[0].resource[0].type = #Subscription
* rest[0].resource[0].extension[0].url = $exp
* rest[0].resource[0].extension[0].valueCode = #SHALL
* rest[0].resource[0].supportedProfile = Canonical(TwiinSubscription)
* rest[0].resource[0].interaction[0].code = #read
* rest[0].resource[0].interaction[0].extension[0].url = $exp
* rest[0].resource[0].interaction[0].extension[0].valueCode = #SHALL
* rest[0].resource[0].interaction[1].code = #update
* rest[0].resource[0].interaction[1].extension[0].url = $exp
* rest[0].resource[0].interaction[1].extension[0].valueCode = #SHALL
* rest[0].resource[0].interaction[1].documentation = "Updating a Subscription: only status off and a change of channel.payload are permitted (TA section Updating a Subscription)."
* rest[0].resource[0].interaction[2].code = #create
* rest[0].resource[0].interaction[2].extension[0].url = $exp
* rest[0].resource[0].interaction[2].extension[0].valueCode = #MAY
* rest[0].resource[0].interaction[2].documentation = "Required where a use-case-specific technical agreement specifies in-band creation for a SubscriptionTopic (TA section Subscription Server)."
* rest[0].resource[0].interaction[3].code = #delete
* rest[0].resource[0].interaction[3].extension[0].url = $exp
* rest[0].resource[0].interaction[3].extension[0].valueCode = #SHOULD-NOT
* rest[0].resource[0].interaction[3].documentation = "A Subscription is ended by setting its status to off, not by deleting it (TA section Sequence Diagram, step 7)."
* rest[0].resource[0].searchParam[0].name = "status"
* rest[0].resource[0].searchParam[0].definition = "http://hl7.org/fhir/SearchParameter/Subscription-status"
* rest[0].resource[0].searchParam[0].type = #token
* rest[0].resource[0].searchParam[0].extension[0].url = $exp
* rest[0].resource[0].searchParam[0].extension[0].valueCode = #SHALL
* rest[0].resource[0].searchParam[1].name = "criteria"
* rest[0].resource[0].searchParam[1].definition = "http://hl7.org/fhir/SearchParameter/Subscription-criteria"
* rest[0].resource[0].searchParam[1].type = #string
* rest[0].resource[0].searchParam[1].extension[0].url = $exp
* rest[0].resource[0].searchParam[1].extension[0].valueCode = #SHALL
* rest[0].resource[0].searchParam[2].name = "url"
* rest[0].resource[0].searchParam[2].definition = "http://hl7.org/fhir/SearchParameter/Subscription-url"
* rest[0].resource[0].searchParam[2].type = #uri
* rest[0].resource[0].searchParam[2].extension[0].url = $exp
* rest[0].resource[0].searchParam[2].extension[0].valueCode = #SHALL
* rest[0].resource[0].searchParam[3].name = "type"
* rest[0].resource[0].searchParam[3].definition = "http://hl7.org/fhir/SearchParameter/Subscription-type"
* rest[0].resource[0].searchParam[3].type = #token
* rest[0].resource[0].searchParam[3].extension[0].url = $exp
* rest[0].resource[0].searchParam[3].extension[0].valueCode = #SHALL
* rest[0].resource[0].searchParam[4].name = "payload"
* rest[0].resource[0].searchParam[4].definition = "http://hl7.org/fhir/SearchParameter/Subscription-payload"
* rest[0].resource[0].searchParam[4].type = #token
* rest[0].resource[0].searchParam[4].extension[0].url = $exp
* rest[0].resource[0].searchParam[4].extension[0].valueCode = #SHALL
* rest[0].resource[0].searchParam[5].name = "payload-type"
* rest[0].resource[0].searchParam[5].definition = "http://hl7.org/fhir/uv/subscriptions-backport/SearchParameter/Subscription-payload-type"
* rest[0].resource[0].searchParam[5].type = #string
* rest[0].resource[0].searchParam[5].extension[0].url = $exp
* rest[0].resource[0].searchParam[5].extension[0].valueCode = #SHALL
* rest[0].resource[0].operation[0].name = "status"
* rest[0].resource[0].operation[0].definition = "http://hl7.org/fhir/uv/subscriptions-backport/OperationDefinition/backport-subscription-status"
* rest[0].resource[0].operation[0].extension[0].url = $exp
* rest[0].resource[0].operation[0].extension[0].valueCode = #SHALL
* rest[0].resource[0].operation[1].name = "events"
* rest[0].resource[0].operation[1].definition = "http://hl7.org/fhir/uv/subscriptions-backport/OperationDefinition/backport-subscription-events"
* rest[0].resource[0].operation[1].extension[0].url = $exp
* rest[0].resource[0].operation[1].extension[0].valueCode = #MAY
